### PR TITLE
Feature: Implemented Loader Component

### PR DESCRIPTION
**Pull request by Peudey**
Loader component implemented with styling and functionality in storybook.

### CODE REVIEW

**Comment by KevinThePepper** [comment]
@Peudey seriously this is great work. I have a couple of recommendations:

- The `inverted` prop is for dark backgrounds. Could you make this text appear and loading icon to be white instead?
- This is nitpicking... Can you make the default text a capital L "Loading"?

Just those 2 changes and I'll mark this as done!

**Review by KevinThePepper — CHANGES_REQUESTED** [review]
- Change styling of component to be white text with a white loader when the `inverted` prop is set to `true`.
- Change the default text value from "loading" to "Loading"

**Comment by KevinThePepper** [comment]
@Peudey can you make the inverted border `#333` instead of `#c7c7c7`? Adds more contrast to the spinning border.

**Comment by Peudey** [comment]
> @Peudey can you make the inverted border `#333` instead of `#c7c7c7`? Adds more contrast to the spinning border.

@KevinThePepper Easy enough, just pushed that change!

**Review by KevinThePepper — APPROVED** [review]

**Pull request merged**
